apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      imagePullSecrets:
        - name: ecr-secret
      containers:
        - name: frontend
          image: danikohale/frontend:latest
          ports:
            - containerPort: 3000
          env:
            - name: REACT_APP_SERVER_URL
              value: "http://LB_backend:8080/employees"
