apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend

          image: 424299668649.dkr.ecr.us-east-1.amazonaws.com/frontend
          ports:
            - containerPort: 3000
          env:
            - name: REACT_APP_API
              value: "http://backend.dev.svc.cluster.local:8080"
