apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: dev 
type: Opaque
stringData:
  DB_HOST: "34.224.169.190"
  DB_USER: "danish"
  DB_PASSWORD: "admin123"
  DB_NAME: "company"
  DB_PORT: "5432"
  ALLOWED_ORIGINS: "http://LoadBlancer-url-frontend:3000"
