name: CI - Build and Push to AWS ECR

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    name: Build and Push Docker Images to ECR
    runs-on: self-hosted

    steps:
   
      - name: Checkout code
        uses: actions/checkout@v4

        - name: Configure AWS credentials
          uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
        
      - name: ECR login
        run: |
            aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 424299668649.dkr.ecr.us-east-1.amazonaws.com
    
      - name: Build and Push Backend Image
        run: |
          docker build -t backend ./backend/Dockerfile
          docker tag backend:latest 424299668649.dkr.ecr.us-east-1.amazonaws.com/backend:latest ./backend
          docker push 424299668649.dkr.ecr.us-east-1.amazonaws.com/backend:latest

   
      - name: Build and Push Frontend Image
        run: |
          docker build -t frontend ./frontend/Dockerfile
          docker tag frontend:latest 424299668649.dkr.ecr.us-east-1.amazonaws.com/frontend:latest ./frontend
          docker push 424299668649.dkr.ecr.us-east-1.amazonaws.com/frontend:latest
       - name: Container
        run: | 
              
            docker run -itd --name frontend -p 3000:3000 424299668649.dkr.ecr.us-east-1.amazonaws.com/frontend:latest
            docker run -itd --name backend -p 8080:8080 424299668649.dkr.ecr.us-east-1.amazonaws.com/backend:latest
